### ISSUE TITLE
Issue w/addDatabaseChangeListener on Android

### ISSUE THREAD

**Issue by tjvantoll** [couchbaselabs/nativescript-couchbase#1]
Hey @nraboy,

I’m trying to document the steps to recreate the issue you’re having so it’s easier for others to jump in and help. The syntax looks fine so everyone is at a loss.

Here’s a brief summation of the problem. Nic is trying to convert the following Java syntax (docs at http://developer.couchbase.com/documentation/mobile/1.2/develop/guides/couchbase-lite/native-api/database/index.html):

``` Java
 db.addChangeListener(new ChangeListener() {
  public void changed(ChangeEvent event) {
    // Process the notification here
  }
});
```

Here’s the [JS equivalent Nic has written](https://github.com/couchbaselabs/nativescript-couchbase/blob/672ca81a5ce821768405c9555b90a546ee580a51/couchbase.android.ts#L108-L112):

``` JavaScript
this.database.addChangeListener(new com.couchbase.lite.Database.ChangeListener({
  changed(event) {
    callback(event);
  }
}));
```

The problem is in Java `event` contains a ton of data, and in JavaScript `event` is undefined. We have no idea why. Here are the steps you can go through to try this out for yourself.

Run these commands to clone the plugin repo and to navigate into the demo:

```
git clone https://github.com/couchbaselabs/nativescript-couchbase.git
cd nativescript-couchbase/demo
```

Then, paste the following in `demo/package.json` to fix a small syntax error:

```
{
  "nativescript": {
    "id": "org.nativescript.CouchbaseProject",
    "tns-android": {
      "version": "1.6.3"
    }
  },
  "dependencies": {
    "nativescript-couchbase": "file:../../nativescript-couchbase",
    "tns-core-modules": "1.6.2"
  }
}
```

Then install dependencies and run the app on Android.

```
tns install
tns run android
```

To hit the change listener you need to have Couchbase’s Sync Gateway running. You need to download it from http://www.couchbase.com/nosql-databases/downloads. (Click on the “Couchbase Mobile” tab. Either the Enterprise Edition or Community Edition is fine.)

Assuming you downloaded the sync gateway to `~/Downloads`, next run the following command:

```
~/Downloads/couchbase-sync-gateway/bin/sync_gateway sync-gateway-config.json
```

With the gateway running head to http://localhost:4985/_admin/ in your browser and click “test-database”. Make some change to the data there are and you should hit the problem in `addChangeListener` for debugging purposes.

**Comment by nraboy** [comment]
Good summary!

So we don't know where the problem is now?

**Comment by tjvantoll** [comment]
Hey @nraboy,

One idea that came up was to try `extend()` to create the instance of `ChangeListener` that you pass into `addChangeListener`. Here are the docs on `extend()` (https://docs.nativescript.org/runtimes/android/generator/how-extend-works.html), and here’s one example of it in use (in the similar callback scenario): https://github.com/sitefinitysteve/nativescript-zendesk/blob/0664ac16693e217e1018a7907006f18a02367efa/plugin/index.android.js#L62. Can you give that a shot and see if it fixes the issue?

**Comment by tjvantoll** [comment]
Had another example from using Facebook’s rebound library. Looks like creating a variable beforehand with `extend()` and passing it in is worth a shot.

```
  var listener = com.facebook.rebound.SimpleSpringListener.extend({
        onSpringAtRest: function (spring) {
            callback();
        }
    });
    mSpring.addListener(new listener);
```

**Comment by tjvantoll** [comment]
Here’s the syntax I’d try to start:

``` javascript
var listener = new com.couchbase.lite.Database.ChangeListener.extend({
  changed(event) {
    callback(event);
  }
});
this.database.addChangeListener(listener);
```

**Comment by nraboy** [comment]
When I make the change, I get the following error:

```
JS: DATABASE LISTENER ERROR Cannot call 'extend' as constructor
```

Just to be clear, my code looks like the following:

```
addDatabaseChangeListener(callback: any) {
    try {
        var listener = new com.couchbase.lite.Database.ChangeListener.extend({
            changed(event) {
                callback(event);
            }
        });
        this.database.addChangeListener(listener);
    } catch (exception) {
        console.error("DATABASE LISTENER ERROR", exception.message);
    }
}
```

**Comment by nraboy** [comment]
I also tried the following and although it didn't error, it did not work as expected:

```
addDatabaseChangeListener(callback: any) {
    try {
        var listener = com.couchbase.lite.Database.ChangeListener.extend({
            changed(event) {
                callback(event);
            }
        });
        this.database.addChangeListener(new listener);
    } catch (exception) {
        console.error("DATABASE LISTENER ERROR", exception.message);
    }
}
```

**Comment by EddyVerbruggen** [comment]
Perhaps I'm looking at a different issue, but after following @tjvantoll's steps and firing up a simulator (Android 6) no crashes occured (like @nraboy's last comment) and the Java objects looks good to me.

A thing to keep in mind is that if you fi. `JSON.stringify(javaObj)` you will see `{}`, but if you inspect it by logging the Java Type `javaObj.getClass().getName()` then it starts to make sense.

So I changed `addDatabaseChangeListener` to this to inspect the object a bit and that's all looking fine to me:

```js
    Couchbase.prototype.addDatabaseChangeListener = function (callback) {
        try {
            this.database.addChangeListener(new com.couchbase.lite.Database.ChangeListener({
                changed: function (event) {
                    console.log("event data: " + JSON.stringify(event)); // {}
                    console.log("event data: " + event.toString()); // JS: event data: com.couchbase.lite.Database$ChangeEvent@757caed
                    console.log("event Java Type: " + event.getClass().getName()); // JS: event data: com.couchbase.lite.Database$ChangeEvent@757caed
                    console.log("event.isExternal(): " + event.isExternal());
                    console.log("event.getSource(): " + event.getSource());
                    var gson = (new com.google.gson.GsonBuilder()).create();
                    console.log("event.getChanges() as JSON: " + gson.toJson(event.getChanges()));

                    // TODO instead of this raw Java Object send a JSON object back
                    callback(event);
                }
            }));
        }
        catch (exception) {
            console.error("DATABASE LISTENER ERROR", exception.message);
        }
    };
```

**Comment by nraboy** [comment]
@EddyVerbruggen you are awesome!

It was there the entire time, I just wasn't handling it correctly.  I am going to play around with it.  @tjvantoll this sounds like great news!

**Comment by burkeholland** [comment]
![qblpg_f-maxage-0](https://cloud.githubusercontent.com/assets/686963/13892501/d60d1c56-ed25-11e5-8d6b-dbcf698ce2cf.gif)
