### ISSUE TITLE
HTTP 500 Application callback block failed

### ISSUE THREAD

**Issue by ryc16** [couchbaselabs/nativescript-couchbase#23]
@nraboy, thanks for your changes. Now I could install this plugin on android platform and able to build and launch.

I try to create a app using this plugin as offline storage which I thought it could do. I followed the demo from "http://blog.couchbase.com/2016/april/couchbase-mobile-in-a-cross-platform-telerik-nativescript-app" without including Couchbase Sync Gateway as I just want it as offline storage.

When I click "Save" and hit below statement 

  var rows = database.executeQuery("people");

I got below error. As offline storage, why HTTP 500? What is missing?

```
The application crashed because of an uncaught exception. You can look at "stackTrace" or "nativeException" for more detailed information about the exception.
com.tns.NativeScriptException: 
Calling js method onCreateView failed
Error: com.couchbase.lite.CouchbaseLiteException: Error when calling map block of view 'people', Status: 593 (HTTP 500 Application callback block failed)
    com.couchbase.lite.store.SQLiteViewStore.updateIndexes(SQLiteViewStore.java:545)
    com.couchbase.lite.View.updateIndexes(View.java:321)
    com.couchbase.lite.View.updateIndex(View.java:294)
    com.couchbase.lite.Database.queryViewNamed(Database.java:2092)
    com.couchbase.lite.Query.run(Query.java:433)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:861)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:726)
    com.tns.Runtime.callJSMethod(Runtime.java:712)
    com.tns.Runtime.callJSMethod(Runtime.java:693)
    com.tns.Runtime.callJSMethod(Runtime.java:683)
    com.tns.FragmentClass.onCreateView(FragmentClass.java:35)
    android.app.Fragment.performCreateView(Fragment.java:1700)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:890)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1062)
    android.app.BackStackRecord.popFromBackStack(BackStackRecord.java:767)
    android.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1542)
    android.app.FragmentManagerImpl$3.run(FragmentManager.java:502)
    android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1447)
    android.app.FragmentManagerImpl$1.run(FragmentManager.java:443)
    android.os.Handler.handleCallback(Handler.java:733)
    android.os.Handler.dispatchMessage(Handler.java:95)
    android.os.Looper.loop(Looper.java:136)
    android.app.ActivityThread.main(ActivityThread.java:5017)
    java.lang.reflect.Method.invokeNative(Native Method)
```

**Comment by nraboy** [comment]
Things have changed slightly in the plugin vs what is found in the writeup, mainly in that you don't have to parse everywhere.  For example:

```
emitter.emit(JSON.parse(document)._id, document);
```

That will become this:

```
emitter.emit(document._id, document);
```

Same applies for querying.

Please take your questions to the comments section of the blog articles that you read.  It makes things easier to keep track of.  The issue tracker is best used for reporting bugs.  I'm happy to help you in the comments section of that article or any other article you read :-)

Best,

**Comment by nraboy** [comment]
Also, when in doubt, look at the two bundled demo applications.  Changes do not happen to the plugin without the demos being updated as well.

**Comment by resquivel24** [comment]
Hello Nic, hope you're doing well.  Nic, I'm working on a project app, and I'm trying to use couchbase lite, to storage a from, that I created in which I use a modal, to obtain the number of guests, smoking, and the date time, to be input into the form.  Now, when I try to get the input of the form and store it using couchbase, it gives me some lots of error.  Now the following link has the logic of my code, could you let me know what I'm doing wrong? [https://i.gyazo.com/0fe9fdadc26292ba5d2405df29400764.png](https://i.gyazo.com/0fe9fdadc26292ba5d2405df29400764.png)
