### ISSUE TITLE
app/couchbaseinstance.ts(1,25): error TS2307: Cannot find module 'nativescript-couchbase'.

### ISSUE THREAD

**Issue by jiwonyune** [couchbaselabs/nativescript-couchbase#25]
```
Found peer TypeScript 1.8.10
app/couchbaseinstance.ts(1,25): error TS2307: Cannot find module 'nativescript-couchbase'.

TypeScript compiler failed with exit code 1
Sending exception report (press Ctrl+C to stop).....

```

I get this error if I don't add this line `/// <reference path="./node_modules/nativescript-couchbase/couchbase.d.ts" /> Needed for autocompletion and compilation.` to **references.d.ts**. This step is not mentioned in **readme.md**. Is this the correct way to approach?

**Comment by nraboy** [comment]
Yes, if you want to use the type definitions you'll have to add that line.  I will add it to the README some time this week.  I encourage you to contribute as well if you'd like to add it to the README :-)

**Comment by jiwonyune** [comment]
Thanks a lot! By the way, how do I contribute to this git regarding this issue? I am relatively new to Github, so there are a few things I don't know yet :(

**Comment by nraboy** [comment]
Way ahead of you @jiwonyune :-)

I've added it to the README already:

https://github.com/couchbaselabs/nativescript-couchbase

In the future, to contribute, fork the repository, make some changes, then create a pull request for me.

Best,
