### ISSUE TITLE
Can't find variable: CBLManager

### ISSUE THREAD

**Issue by eurica-larazo** [couchbaselabs/nativescript-couchbase#27]
I added the plugin using this command:

`tns plugin add nativescript-couchbase`

And when i tried to use it, its giving me an error:

`NativeScriptError: ReferenceError: Can't find variable: CBLManager`

**Comment by nraboy** [comment]
I just tried adding the plugin to a fresh project and running for iOS.  I did not run into any problems.

Do you have a Mac?  You cannot build for iOS if you don't have a Mac.  If you do have a Mac, please list all your software versions:

1. Xcode
2. NativeScript
3. iOS Emulator

Best,

**Comment by eurica-larazo** [comment]
Yes Im using Mac.
XCode - 7.3.1
NativeScript - 2.1.1
iOS Emulator - 9.3 (iPhone 6)

It actually works now, I really don't know what happened to my copy but when restart my computer it finally works. But still thanks for quick response.

**Comment by nraboy** [comment]
No worries, you had a very valid concern :-)

Feel free to reach out in the forums if you have any Couchbase questions or want to learn about best practices:

https://forums.couchbase.com/

**Comment by jruef** [comment]
@nraboy Hi, I'm getting the same error

I have Xcode 8.2, tns 2.4.0 and emulator is iPhone6

I would really like to use your plugin :-)

**Comment by nraboy** [comment]
When you use this plugin, like any NativeScript plugin, you have to build and deploy the project before trying to use `livesync`.  I see this error a lot when people try to `livesync` before the project with plugin had been deployed.

The thing about `livesync` is that it only deploys HTML, TypeScript, and CSS data, not plugin data.  Once the project has been deployed with all the plugins, then `livesync` would work.

This plugin should work fine on iOS 8, even though iOS 8 is considered ancient by now.

Best,

**Comment by jruef** [comment]
@nraboy thanks for your fast reply, maybe i have a different error, i ran `tns deploy ios` and i get 

```
CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:344:22: Error: Uncaught (in promise): ReferenceError: Metadata for "CouchbaseLite.CBLManager" found but symbol not available at runtime.
```

I get the same error when i run `tns livesync ios --watch --emulator`

Thx for your help

**Comment by nraboy** [comment]
I'm not sure what `tns deploy` does, but I can confirm this works:

```
tns emulate ios
tns livesync ios --emulator --watch
```

The first command will deploy it to the iOS simulator and run it.  On future runs, you can just do `livesync` since the plugin had already been deployed.

@tjvantoll care to comment on what `tns deploy` does and why it won't work in this scenario?  Also, is iOS 8 still supported in NativeScript?

Best,

**Comment by jruef** [comment]
@nraboy thx for the hint. I got it to work, here are the steps

1. Delete the `lib` folder
2. `tns emulate ios` wait until app started successfully in simulator
3. `tns livesync ios --emulator --watch`

Therefore i can confirm that nativescript-couchbase plugin 1.0.16 is running on tns 2.4.0 with xcode 8.2 and iPhone 6 simulator with iOS 10.

Best

**Comment by nraboy** [comment]
Glad you got it.  This applies to all third-party plugins.  Just the way live-reload works.

Best,
