### ISSUE TITLE
JS: MANAGER ERROR: Cannot read property 'lite' of undefined

### ISSUE THREAD

**Issue by sarvagayatri** [couchbaselabs/nativescript-couchbase#36]
Hi,
`this.database = new couchbaseModule.Couchbase("my-database");`
i am working on nativescript angular2 app.
working fine with the new app, and the same command giving error in my working app like : 
**JS: MANAGER ERROR: Cannot read property 'lite' of undefined**

i removed the plugin, added again in my working app, but still popping up same error

Please give the solution

**Comment by sarvagayatri** [comment]
while debugging, in the com Object, i am getting only android, tns and not getting couchbase. what could be the reason ?

```
var Couchbase = (function () {
    function Couchbase(databaseName) {
        this.context = applicationModule.android.context;
        try {
            this.manager = new com.couchbase.lite.Manager(new com.couchbase.lite.android.AndroidContext(this.context), null);
            this.database = this.manager.getDatabase(databaseName);
        }
        catch (exception) {
            console.error("MANAGER ERROR:", exception.message);
        }
    }
```

**Comment by nraboy** [comment]
So you're saying it is working fine for Android, but not iOS?  Are you sure the plugin was added correctly for both platforms?  I've run into strange things occasionally where plugins in general don't add correctly.

What versions of everything are you using?

cc @hodgreeley

**Comment by sarvagayatri** [comment]
tns --version : 2.2.1
node --version : v5.1.0
"tns-core-modules": "2.3.0",
Both my sample n working apps are on android. for new app couchbase working fine. but with my practise app which is already having few other files not working fine. giving manager error: Lite of undefined.
i deleted node modules and added the plugins again. but still same problem persists.

**Comment by nraboy** [comment]
So just to be clear, the plugin works fine in new apps, but doesn't work in the provided demos.  Is this correct?

**Comment by sarvagayatri** [comment]
yess

**Comment by nraboy** [comment]
The demos will be updated soon with the latest Angular and CLI changes.  They are using some pretty old dependencies.

I'll post back when they're good.

Best,

cc @hodgreeley

**Comment by sivamamidi-REISys** [comment]
we also facing same issues.

**Comment by sivamamidi-REISys** [comment]
Facing same issue with new repositories as well.

**Comment by nraboy** [comment]
@sivamamidi-REISys,

A few days ago I updated both the vanilla and Angular 2 demos https://github.com/couchbaselabs/nativescript-couchbase/commit/2ddeaae5e55570be9042d06639cc84a1bfcf3f90 and tested them with the latest version of the plugin.  They worked without issue.

What kind of errors are you receiving?  How are you preparing the demos? Is this for both iOS and Android?

Best,

**Comment by sivamamidi-REISys** [comment]
JS: MANAGER ERROR: Cannot read property 'lite' of undefined, 
Nativescript : Latest version
Android : Google Nexus 7, API 23

**Comment by nraboy** [comment]
Can you put your project on GitHub?  I just tested the demos and the plugin and they work fine for me.

**Comment by sivamamidi-REISys** [comment]
Thank you nraboy for quick response. Surprisingly i just created an sample app it's working fine. So i just deleted node_modules and platform folder in previous solution and did npm install and added platforms. it's started working.

**Comment by nraboy** [comment]
Ah sounds like the classic, NPM didn't clean up my dependencies properly, issue :-)

Glad you got it working!

**Comment by nraboy** [comment]
This seems to be fixed now.
