### ISSUE TITLE
Database isn't persisted after reboot of android (device or emulator)

### ISSUE THREAD

**Issue by mcordes** [couchbaselabs/nativescript-couchbase#39]
Hi, 

Thanks for a great library. I'm running into an issue (which is entirely likely to be user error). I'm able to create a database, insert data, run a query and everything work great. When I restart the android emulator (or device) the database seems to no longer exist (my query now returns no results. 

Is this an artifact of running using 'tns run android'? 

Is there some extra step I need to do to actually commit and persist my changes? 

Can changes actually be persisted locally? I'm not intending to sync server and just want to persist the data on the device. 

Any other suggestions?

**Comment by nraboy** [comment]
Hey @mcordes,

The data is persisted locally.  So here is what I've noticed when relaunching things via the NativeScript CLI.  Occasionally when you re-run `tns emulate` or `tns run`, the application data is reset.  It has happened on other events beyond Couchbase, and I'm not sure why.

Upgrading your application outside of the CLI, should retain all your data.

Best,
