### ISSUE TITLE
Is it possible to ship an app with a baseline DB?

### ISSUE THREAD

**Issue by chrishaff** [couchbaselabs/nativescript-couchbase#51]
This may be more of a basic Couchbase questions, but is it possible to ship a _moment in time_ copy of a database in the app bundle that would then sync when the app is run?  

You know, as a head start of sync time and also to work out of the box if the device is not online.

In some versions of PouchDB/CouchDB they essentially end up using SQLite as the store, so you can ship that.  Is this also possible with this implementation of Couchbase?

Thanks!

**Comment by nraboy** [comment]
There is a way to ship with a pre-built database.  Please take this question to the forums as the issue tracker is more for bugs and feature requests.

https://forums.couchbase.com

Best,
