### ISSUE TITLE
[Question] Can I export and import database in my app?

### ISSUE THREAD

**Issue by gaurav-chandra** [couchbaselabs/nativescript-couchbase#57]
Can I export and import database in my app? I don't want to use the sync gateway. Is this possible?

**Comment by nraboy** [comment]
You do not need Sync Gateway to use this plugin as it is based around Couchbase Lite.  To import and export, you'll have to add this logic to your application.  There is no way to copy a pre-filled database in and take a database out.  This can only be done by writing your own logic.

Best,
