### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by rmaugusto** [couchbaselabs/nativescript-couchbase#60]
I tried to create a document but the data was not canonical and I just got it because of console log.
Reviewing the plugin source code I could notice it never throws an exception but executes "console.error".
My suggestion is throw the exception for a correct exception handling from client.

**Comment by nraboy** [comment]
Pull requests are appreciated :-)

**Comment by rmaugusto** [comment]
With pleasure...

**Comment by nraboy** [comment]
Merged https://github.com/couchbaselabs/nativescript-couchbase/pull/62
