### ISSUE TITLE
Remove/destroy all

### ISSUE THREAD

**Issue by carrbrpoa** [couchbaselabs/nativescript-couchbase#61]
Hello,
Is there an easy way to clear/remove/destroy every database created in an app? (I create one couchbase instance per "entity" type I persist)

**Comment by nraboy** [comment]
You could call the `destroyDatabase` method to completely remove the local database. You can also call the `deleteDocument` method to delete particular documents by id.

https://github.com/couchbaselabs/nativescript-couchbase/blob/master/couchbase.d.ts
