### ISSUE TITLE
Syncing doucment based on parameter

### ISSUE THREAD

**Issue by chandansutradhar2** [couchbaselabs/nativescript-couchbase#65]
I have couchbase sever with one bucket consisting of 1 million documents for 50 cities transportation like train and subways. I want to replicate and download only relevant city document at the start of nativescript app based on user selection of cities.How can i enable conditional sync of only relevant document based on cityID ?

basically i am looking for something like this 
        this.couchbaseInstance.startSync(true,'boston'); /* Where boston is city ID  . So that only Boston city documents are downloaded*/  

Thanks

**Comment by silveirado** [comment]
Hi @chandansutradhar2 I have a little trick to do that:
first, on your sync gateway, override the sync function to create channel with the cityID, like this: `"sync": "function(doc) {channel(doc.cityID)};",`.

And then create a sync start function on nativescript, like that:
`
import { isIOS } from 'tns-core-modules/platform';
import { Couchbase } from 'nativescript-couchbase';

....
    this._couch = new Couchbase(YOUR_LOCALDB);
    this._pull = this._couch.createPullReplication(YOUR_SYNCGATEWAY_URL);
    this._pull.setContinuous(true);
    if (isIOS) {
      this._pull.replicator.channels = [CITY];
    } else {
      this._pull.replicator.setChannels([CITY]);
    }
    this._pull.start();
`
this works for me, I hope to helped you with this code.

**Comment by chandansutradhar2** [comment]
Thanks a ton @silveirado!!!. It works now.
