### ISSUE TITLE
Couchbase Lite 2.0 compatibility

### ISSUE THREAD

**Issue by grreeenn** [couchbaselabs/nativescript-couchbase#82]
Hello,

Will the plugin work 2.0 version of Couchbase Lite?
If not, are there any plans to continue development? Asking because the last commit had been 9 months ago...

Thank you!

**Comment by razorsyntax** [comment]
Agreed.  Support for this would be appreciated.

**Comment by geraldapeoples** [comment]
I agree too. It would be very much appreciated.

**Comment by borrrden** [comment]
https://github.com/triniwiz/nativescript-couchbase-plugin This repo supports Couchbase Lite 2.x.  This repo is not being maintained.
