### ISSUE TITLE
Upgrade to NativeScript 4

### ISSUE THREAD

**Issue by simonox** [couchbaselabs/nativescript-couchbase#89]
Are there any plans to upgrade this plugin to {N} 4.0.1. It is still using {N} 3:

```    
   "devDependencies": {
        "tns-core-modules": "^3.0.0",
        "tns-platform-declarations": "^3.0.0",
        "typescript": "^2.2.2"
    }
```

**Comment by OliverNiebsch** [comment]
There is already a pull request ( #83 ).
I really would like to update my app to Nativescript4. Would it be possible to merge the pull request soon? @nraboy

**Comment by nraboy** [comment]
I just commented on the PR. Adding @hodgreeley since he is in charge of mobile projects at Couchbase.

**Comment by ludwiktrammer** [comment]
Is there any news on this front?

**Comment by razorsyntax** [comment]
Do we have enough interest here to fork this and continue development?

**Comment by SaltyDH** [comment]
Just a heads up, NS5 is slated for "October" on the roadmap ;)

**Comment by borrrden** [comment]
No action will be taken on this as this repo is not being maintained.
