### ISSUE TITLE
add custom ID to the createDocument function

### ISSUE THREAD

**Issue by nicHoch** [couchbaselabs/nativescript-couchbase#9]
it would be very helpfull if the plugin would support custom document ids

something like this will do:

createDocument(data: Object, id? : string) {
...
} 

thanks Nicky

**Comment by nraboy** [comment]
That is a great idea!

I left a lot to be desired in the plugin.  Wanted to get the core features in there first.

I'll get this feature included soon.

Thanks,

**Comment by nraboy** [comment]
This has been added to commit https://github.com/couchbaselabs/nativescript-couchbase/commit/821506c60ee668d8da2760dbd8b5dc88e1b1ea14 on the development branch.  It will be merged into the master branch after some testing is done.

**Comment by nraboy** [comment]
This is available as of version 1.0.7
