### ISSUE TITLE
Update Readme to include "No Longer Supported"

### ISSUE THREAD

**Issue by Eonfuzz** [couchbaselabs/nativescript-couchbase#90]
It has been a year since the last major update, the repo doesn't support Nativescript v4 and there are still several major issues with the iOS implementation.

**Comment by geraldapeoples** [comment]
@dimm0 Have a look at https://github.com/triniwiz/nativescript-couchbase-plugin

**Comment by dimm0** [comment]
Hmm, getting a similar error... `TypeError: Cannot read property 'lite' of undefined`

**Comment by borrrden** [comment]
This has been taken care of.  I'll add a recommendation for the above as I am surprised to see that it supports Couchbase Lite 2.x
