### ISSUE TITLE
Upgrade to NativeScript 5

### ISSUE THREAD

**Issue by razorsyntax** [couchbaselabs/nativescript-couchbase#91]
Any information on this roadmap?

**Comment by NickIliev** [comment]
@razorsyntax is there any specific issue for using the plugin with NativeScript 5.x.x. I've created t[his simple demo](https://github.com/NickIliev/NS-Issues-2019-I/tree/master/others/t-1384958) and it works as expected on my side.

**Comment by razorsyntax** [comment]
I guess you're right.  It's working.  I was getting worry seeing the warning message about v5.0.0 when I built the app.  It's definitely not broken.

**Comment by borrrden** [comment]
No action will be taken for any upgrades as this repo is not being maintained.
